name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Verify
              run: node ./common/scripts/install-run-rush.js change --verify
            - name: Prettier
              run: node ./common/scripts/install-run-rush.js prettier-check
            - name: Install
              run: node ./common/scripts/install-run-rush.js install
            - name: Build
              run: node ./common/scripts/install-run-rush.js build --verbose
