name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    install:
        name: Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Rush install
              run: node ./common/scripts/install-run-rush.js install
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: install
        steps:
            - run: node ./common/scripts/install-run-rush.js build --verbose
    prettier:
        name: Prettier
        needs: install
        runs-on: ubuntu-latest
        steps:
            - run: node ./common/scripts/install-run-rush.js prettier-check
    verify:
        name: Verify
        runs-on: ubuntu-latest
        needs: install
        steps:
            - run: node ./common/scripts/install-run-rush.js change --verify
