name: Publish
on: workflow_dispatch
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  git config --local user.email ${{ github.actor }}@users.noreply.github.com
                  git config --local user.name ${{ github.actor }}
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install
              run: node ./common/scripts/install-run-rush.js install
            - name: Build
              run: node ./common/scripts/install-run-rush.js build --verbose
            - name: Version
              run: node ./common/scripts/install-run-rush.js version --bump --target-branch main
            - name: Publish
              run: node ./common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch main --add-commit-details
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
