name: Publish
on: workflow_dispatch
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Rush install
              run: node ./common/scripts/install-run-rush.js install
            - name: Rush build
              run: node ./common/scripts/install-run-rush.js build --verbose
            - name: Rush publish
              run: node ./common/scripts/install-run-rush.js publish
